### ISSUE TITLE
千万不要使用cnpm命令来install！

### ISSUE THREAD

**Issue by Nyaasu66** [amphineko/amphineko#14]
千万不要使用cnpm命令来install！会出现无限循环子目录的bug！这个过程中CPU会一直满载，而且删除过程及其漫长，建议把这个提示加在README.md里

**Comment by amphineko** [comment]
你好，因为我不是 cnpm 用户，所以没有办法复现你的问题。

如果可以的话，希望你可以提供一下 verbose 日志，或者说明一下这个 cnpm 的 bug 和这个 repo 的关系，不然我不能因为这个原因在 README 里推荐用户不使用 cnpm。

PS: 如果你遇到 npm 的连接障碍的话，可以考虑配置使用淘宝的 npm 镜像而不一定非要使用 cnpm。

**Comment by Nyaasu66** [comment]
关于详细的日志，暂时不知道如何获取，因为是个 npm 小白。
 
录了一段 gif 复现了一下这个bug

![aboutme-cnpm-bug](https://user-images.githubusercontent.com/32192232/70336324-ed587080-1883-11ea-90a0-2706a63397c6.gif)

**Comment by amphineko** [comment]
如果你只是想要安装这个 repo 的依赖的话，我建议你直接使用 npm 看一下能不能解决这个问题。

你可以参考下面这个命令来设置 npm 的镜像
```
npm config set registry https://registry.npm.taobao.org
```
或者在安装的时候临时指定 registry
```
npm install . --registry=https://registry.npm.taobao.org
```

**Comment by Nyaasu66** [comment]
我在windows上使用npm安装，node-sass会build失败，于是我使用ubuntu进行Build，最后成功了，谢谢你的帮助

**Comment by amphineko** [comment]
在 Windows 上的 node-sass 的安装问题请参考 README.md 最后部分的内容

**Comment by Nyaasu66** [comment]
事实上我已经按照 README.md 最后部分更改了源，但是依旧安装失败。经过百度发现是node最新版本与node-sass4.11不兼容的问题，于是我使用ubuntu上的旧版本node build成功了。(全程都使用了科学上网)，再次谢谢你的帮助～
