### ISSUE TITLE
在移動端下，點擊設為 cursor: not-allowed; 的元素會因爲該元素設置了空的超鏈接而跳轉至頂部。

### ISSUE THREAD

**Issue by MashiroUsagi** [amphineko/amphineko#21]
在移動端下，點擊設為 cursor: not-allowed; 的元素會因爲該元素設置了空的超鏈接而跳轉至頂部。需要解決，描述不清敬請諒解。

**Comment by amphineko** [comment]
https://github.com/amphineko/amphineko/blob/3e1c266ab062d05070d97935903cfa80898abecf/src/index.html#L137

TODO: allow both `<a>` link and `<div>` pseudo here.

**Comment by MashiroUsagi** [comment]
多谢提醒，已解决。
