### ISSUE TITLE
小白提问，怎样配置才能让最新更改显示到网页

### ISSUE THREAD

**Issue by Redstone-ray** [amphineko/amphineko#22]
你好，现在我更改任何文件都是在master branch更改，但是github用的是gh-pages branch来部署网站，请问怎么配置才能让我的更改在网站上显示出来

**Comment by amphineko** [comment]
Hello，请你参考一下 README 里关于 build 的说明。当你运行完 `npm run build` 完成 webpack 工作之后，dist 目录中的文件即是你需要部署到服务器的输出。

**Comment by Redstone-ray** [comment]
明白了，谢谢
